version: "3.7"
services:
  backend:
    container_name: "traceable"
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=prod
      - hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - MYSQL_HOST=traceable-db
      - SPRING_DATASOURCE_URL=jdbc:mysql://traceable-db:3306/appDb?autoReconnect=true&useSSL=false
    networks:
      - traceable-network
    depends_on:
      - traceable-db

  traceable-db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myUserPass
      MYSQL_DATABASE: appDb
      MYSQL_USER: myUser
      MYSQL_PASSWORD: myUser
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-appdb-volume:/var/lib/mysql
    networks:
      - traceable-network
  # Names our volume

volumes:
  mysql-appdb-volume:

networks:
  traceable-network:
