version: "3.7"
services:
  mssql-db:
    container_name: "mssql-db"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: db-wrz2z
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql/data
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "8081:8081"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8081
      - LAMBDA_EXECUTOR=local
      - KINESIS_ERROR_PROBABILITY=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mssql-data:

networks:
  todo-list-network: