# common.properties
info:
  description: Global configuration
# springboot profiles
profile: ${spring.profiles.active}  
# sping.properties
spring:
  datasource:
    url: jdbc:postgresql://testdb.c0o9e23tkjbi.us-east-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: postgres
#    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    basic:
      enabled: false
