# common.properties
info:
  description: Global configuration

profile: ${spring.profiles.active}  

spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:testdb.c0o9e23tkjbi.us-east-2.rds.amazonaws.com}:${RDS_PORT:5432}/${RDS_DB_NAME:postgres}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    basic:
      enabled: false
